### ISSUE TITLE
The regression is not always robust for common SNPs

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#74]
Look at this example:
![chr9_32541532_32541532_a_g](https://cloud.githubusercontent.com/assets/3366818/10816404/e629a1ca-7e32-11e5-9fa2-83a244f1c9fb.jpg)
I think we can safely exclude AF>0.25 before fitting the regression to avoid this?

**Comment by tdelhomme** [comment]
To deals with this, we implemented the option `--extra_robust_gl`: if between `10` and `50%` of samples have an allelic fraction higher than `20%` and if excluding them it remains at least `10` samples, we compute the regression without these outliers and re-add them at the end to compute the q-values. Otherwise, we take the default behaviour.
